### PR TITLE
Create Rise-Come Together

### PR DESCRIPTION
**Pull request by projmersch**

### CODE REVIEW

**Comment by ehedaya** [comment]
@projmersch looks good, can you rename the file to have a .txt extension?

**Comment by projmersch** [comment]
Hi Emil- I'm not sure how to rename the file with a txt extension. I'll keep looking. I made one other tab awhile ago and figured it out so hoping it works. I have tabbed out Thread as well which I will send up once Rise works.

**Comment by projmersch** [comment]
Maybe that worked?

**Comment by ehedaya** [comment]
Looks like it, thanks!

**Pull request merged**
