### PR TITLE
Create Split Open and Melt

### PR DESCRIPTION
**Pull request by cactusbass**

### CODE REVIEW

**Comment by cactusbass** [comment]
Hey there! Thanks as always for your work in maintaining this incredible
resource. Curious, is there a reason I don't see this live yet?

**Comment by cactusbass** [comment]
Any word on this? Did I do something wrong with the submission? Thanks!

**Comment by cactusbass** [comment]
@ehedaya any thoughts? ^

**Comment by ehedaya** [comment]
@cactusbass hey sorry I missed your note! I think the reason it didn't show up is that you added it in `bass/`, not `files/bass/`.  It was in the repo but wasn't getting picked up by the index.

https://emilstabs.org/bass/Split%20Open%20and%20Melt.txt

Anyhow it's live now.  Thanks again!

Emil

**Comment by cactusbass** [comment]
Got it. Thx!!

**Pull request merged**
