### PR TITLE
Create ...And Flew Away.txt

### PR DESCRIPTION
**Pull request by wanestar**
Create ...And Flew Away.txt

### CODE REVIEW

**Comment by ehedaya** [comment]
Thanks for your contribution, sorry for the delay!

**Comment by wanestar** [comment]
While you're still around it seems like this tab isn't displaying on the website. I'm guessing it is the ... in the name?

**Comment by readicculus** [comment]
I reached out to Emil to see if I could help at all with maintaining.  He mentioned deployments are not automated, I'm guessing since he got through the PRs today he will probably deploy soon when he has time!

**Comment by wanestar** [comment]
Makes sense! Still I feel it could be a bug as the other PR's (The Well, Oblivion etc.) all display fine. Well I guess we will see what happens in time.

**Pull request merged**
